#ranyanhao@wind-mobi.com 20160104 begin
$(info lucifer windDeviceInfo $(CONFIG_WIND_DEVICE_INFO))
obj-$(CONFIG_WIND_DEVICE_INFO) += wind_device_info.o
#obj-y += wind_device_info.o

#ranyanhao@wind-mobi.com 20160104 end
